### ISSUE TITLE
[Bug] Enabling breaks pf2e chat card buttons

### ISSUE THREAD

**Issue by esheyw** [jsavko/chat-timestamp#1]
Tested with no other modules active. https://i.imgur.com/MOUEib1.png https://i.imgur.com/q35Ktwc.png none of these buttons function with this module active. Too bad, because I would very much like to use it 😞

**Comment by jsavko** [comment]
I will give it a test in a pathfinder world.  I don't play pathfinder, so I never tested it with that system

**Comment by jsavko** [comment]
I've just pushed an update that fixes the issue.  An update of the module should get things cleared up

**Comment by esheyw** [comment]
Can confirm, that fixed it, ty 😊
