### ISSUE TITLE
Feature request: get timestamp from Simple Calendar

### ISSUE THREAD

**Issue by asherett** [jsavko/chat-timestamp#7]
Hi! I really like this little module. 
Here's a challenge if you want to give it a shot, see if you can add an option to get time/date from the Simple Calendar module. (ie. display ingame time instead of RL time)
Simple Calendar should have an API etc to make this quite possible.
https://foundryvtt.com/packages/foundryvtt-simple-calendar

**Comment by asherett** [comment]
Closed without comment? Will not develop, or...?

**Comment by jsavko** [comment]
I accept pull requests.
