### ISSUE TITLE
[Request] Options For Time Format

### ISSUE THREAD

**Issue by SophieScott12** [jsavko/chat-timestamp#8]
It would be great to have the ability to change how time is formatted, for example to have a 24-hr time format or for the date to be day-first instead of month-first.

**Comment by jsavko** [comment]
Manually editing the template files would give you that flexibility.  It's not something that is easily implemented from a configuration standpoint

**Comment by SophieScott12** [comment]
Would you like to explain how to do that, then?  Because if I saw any way to change the format in any of the files, I would have done it myself.
